language: node_js
  - "stable"

cache:
  directories:
  - node_modules
services:
  - docker
script: 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t $DOCKER_USERNAME/reactapp:v4 .
  - docker push $DOCKER_USERNAME/reactapp:v4
