language: node_js
  - "stable"
before_install:
  - echo "BEFORE INSTALL START"
  - gem install bundler
  - echo "BEFORE INSTALL END"

env:
  - NODE_ENV="development"
  - NODE_ENV="Production"
cache:
  directories:
  - node_modules
services:
  - docker
script: 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t $DOCKER_USERNAME/reactapp:v3 .
  - docker push $DOCKER_USERNAME/reactapp:v3
